AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'lazy_rotator.gemspec'
    - 'spec/**/*'

Style/MutableConstant:
  Exclude:
    - 'lib/lazy_rotator/version.rb'
