plugins:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'lazy_rotator.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/MutableConstant:
  Exclude:
    - 'lib/lazy_rotator/version.rb'
