#!/bin/bash

versions=('3.2.8' '3.3.8' '3.4.2')

switcher=`which asdf`
if [[ $switcher = *[!\ ]* ]]; then
  verb="local ruby"
else
  switcher=`which rbenv`
  if [[ $switcher = *[!\ ]* ]]; then
    verb="local"
  else
    switcher=`which rvm`
    if [[ $switcher = *[!\ ]* ]]; then
      verb="use"
    else
      echo "Please install asdf, rbenv, or rvm"
      exit 1
    fi
  fi
fi

bundle_exec() {
  local cmd="$1"
  local version="$2"
  echo "Run $cmd with Ruby $version"
  eval "$switcher $verb $version"
  if [[ -f "Gemfile.lock.$version" ]]; then
    eval "cp Gemfile.lock.$version Gemfile.lock"
  else
    echo "Please run ./all_rubies bundle first"
  fi
  bundle exec $cmd
}

case "$1" in
  bundle)
    for version in ${versions[@]}
    do
      echo "Bundle for Ruby $version"
      eval "$switcher $verb $version"
      rm Gemfile.lock
      if [[ -f "Gemfile.lock.$version" ]]; then
        eval "cp Gemfile.lock.$version Gemfile.lock"
      fi
      gem list --local bundler | grep bundler || gem install bundler --no-ri --no-rdoc
      gem update bundler
      bundle install --path vendor/bundle
      bundle update
      eval "cp Gemfile.lock Gemfile.lock.$version"
    done
    ;;

  cop)
    bundle_exec "rubocop" ${versions[0]}
    ;;

  spec)
    for version in ${versions[@]}
    do
      bundle_exec "rspec spec" $version
    done
    ;;

  *)
    echo $"Usage: $0 {bundle|spec|cop}"
    exit 1
esac

exit 0
